//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarDetails = new HashSet<CarDetail>();
            this.Pictures = new HashSet<Picture>();
            this.XrefUserCars = new HashSet<XrefUserCar>();
        }
    
        public int Id { get; set; }
        public int BrandId { get; set; }
        public int CarModelId { get; set; }
        public decimal Price { get; set; }
        public string City { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> PetrolTypeId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual CarModel CarModel { get; set; }
        public virtual PetrolType PetrolType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarDetail> CarDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XrefUserCar> XrefUserCars { get; set; }
    }
}
