//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarDetail()
        {
            this.Pictures = new HashSet<Picture>();
        }
    
        public int Id { get; set; }
        public int CarId { get; set; }
        public int BodyId { get; set; }
        public int TransmissionId { get; set; }
        public int ConditionId { get; set; }
        public string Description { get; set; }
    
        public virtual Body Body { get; set; }
        public virtual Car Car { get; set; }
        public virtual TechnicalCondition TechnicalCondition { get; set; }
        public virtual Transmission Transmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
