//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarDBEntities1 : DbContext
    {
        public CarDBEntities1()
            : base("name=CarDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Body> Bodies { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarDetail> CarDetails { get; set; }
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<PetrolType> PetrolTypes { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<TechnicalCondition> TechnicalConditions { get; set; }
        public virtual DbSet<Transmission> Transmissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<XrefUserCar> XrefUserCars { get; set; }
    }
}
