//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Id { get; set; }
        public string PicturePath { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> CarDetailsId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual CarDetail CarDetail { get; set; }
    }
}
